### ISSUE TITLE
about the inference.

### ISSUE THREAD

**Issue by ZHUXUHAN** [visinf/veto#1]
Hi, I have some thoughts on your approach:
It seems that you ensemble the results of different models, which may cause an object pair to have more than one predicted relationship during the test, which does not meet the current unlimited sgg rules. As far as I know, all the methods you compared are with constraint, that is, only the top1 result of the current object pair is considered to be the predicate of the last evaluation.

**Comment by GopikaSudhakaran** [comment]
Hi, we have also repoduced our ensemble setting on the baselines (baseline + MEET), also report the  rwt VETO (SOTA A@k for PredCls & SGCls) without ensembling results.  It's important to observe that  ensembling alone doesn't ensure improvement (eg: for VTransE + MEET there is perfomance drop rather than increase), as demonstrated by the substantial advancements seen in VETO + MEET compared to baseline + MEET. Our primary objective is to enhance predictions for both prominent and less prominent categories. Notably, top-performing models experience a considerable drop in performance for major classes in their pursuit of state-of-the-art status.

**Comment by ZHUXUHAN** [comment]
I apologize for the misunderstanding. What I meant is that your MEET method assigns more than one relationship to each object pair during the inference stage, which actually violates the current constrained rules. Your method should be evaluated using unconstrained metrics. The improvement demonstrated by MEET seems excessively pronounced, prompting a consideration of the fairness of your comparisons. However, I acknowledge that VETO appears to excel particularly in predcls, but you should also compare it against PENET (CVPR2023). When it comes to precision, it's possible that you cannot classify it as the State-of-the-Art (SOTA).

**Comment by GopikaSudhakaran** [comment]
Hi thank you for your suggestions, 
1) It would be interesting to evaluate under additional settings including precision which could go as an extension. The MEET is constrained under the expert setting unlike unconstrained, because of OOD based training the confidence of less probable pairs will be reduced so future works could use MEET for improved hits within top@k where k denote number of experts. 
Once again we were trying to increase the hits within the constrained range and not every model could improve under this range even after using MEET like VTransE + MEET. 

Following is the requested comparison of VETO against unconstrained for PredCls task. Please note that any additional experiments is out of scope of this project and could be analysed in future works. 
![image](https://github.com/visinf/veto/assets/45491358/60002bab-2b6e-4930-b248-62f0c34459ef)

2) We made our submission on 8th March & PENET was out on the 14th of March and ofcourse the SOTA status is evolving.

**Comment by ZHUXUHAN** [comment]
First of all, thank you for your hard work and diligent responses. I believe that this is very helpful not only for me but also for other followers.

According to the description of the MEET method in the paper, it is indeed the case that other methods are limited to evaluating only the top-1 relationship for each object pair, rather than the top-K relationships.

Furthermore, setting a top-K constraint seems unreasonable. Based on the unrestricted setting you provided, the metrics show a significantly better performance in terms of Recall and mean Recall compared to the MEET method described in the paper. I think this constraint is unnecessary and, in fact, leads to a decrease in accuracy. We can directly use the predictions from the unrestricted setting. Also, even though PENET came after your work, the RUNET method (CVPR 2022) should also be considered for comparison.

Additionally, as a side note, I don't believe that the current use of TOP-1 is a good choice. From a perspective of fair comparison, at this stage, it's still necessary to restrict the evaluation to only compare the top-1 predictions. Furthermore, the rationale behind its existence is to test the model's generalization ability in detecting fundamental relationships. I believe it serves a necessary purpose.

**Comment by ZHUXUHAN** [comment]
To add further, if you are to randomly set TOP-2 or TOP-k, I believe you would still achieve results that are fairly similar to those reported in your paper. Hence, I believe this could serve as a new metric, namely the comparison under the Top-n setting.

But I think it's not meaningful because, it should suffice to have no limitations at all, i.e., without scene graph constraints (Neural Motifs: Scene Graph Parsing with Global Context).


Furthermore, what I still want to convey is that you've done a fantastic job, and I appreciate your responses. As a researcher in this field, I'm eager to witness a significant breakthrough. However, due to limitations in datasets and shortcomings in methods, the development in this field is still challenging. Nevertheless, your work has indeed provided me and others with valuable insights.

**Comment by GopikaSudhakaran** [comment]
First of all thank you for sharing your thoughts and showing interest in our work,
I would like to share our perspective on why we thought this setting might be useful.
Our perspective is that as we are not taking topk from the entire relations rather it is top1 from each expert SGG relations such as on(from head expert)/walking on(from tail expert) could be captured were both are meaning full. If we go for top k on entire relations this might result in more False Positives from overconfident classifier predictions under the uncalibrated MEET setting that is the 2nd best (eg:in) from first classifier might be overconfident and be the 2nd best prediction than “walking on” from the tail(evaluation on precision could be done in future). However I agree that having topk from the entire relations could also be a useful comparison ablation.  Also under unconstrained results setting from the models that’s used other debiasing techniques, we could see that MEET is indeed helpful at improving tail classes without dropping on head classes. I believe there are amazing future research extensions possible to further evaluate and improve the MEET setup. 
Having varied top-n metric is difficult because there are many possibilities this is why we used the split proposed in SHA+GCL paper. Future works could also use the same split proposed by SHA+GCL authors if they wish to report their models effectiveness under this setup.
